"""Initial Migration

Revision ID: 38f339f4af11
Revises: 
Create Date: 2018-04-23 16:52:24.819053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f339f4af11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_number', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
